# Generated by Django 6.0 on 2025-12-28 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_alter_vulnerability_payload'),
        ('users', '0002_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Full address'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.TextField(blank=True, help_text='Company address'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_country',
            field=models.CharField(blank=True, help_text='ISO country code', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company/Organization name', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='company_registration_number',
            field=models.CharField(blank=True, help_text='Registration/VAT number', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='company_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='International format: +359XXXXXXXXX', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verification_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_members', models.IntegerField(default=10, help_text='Maximum team members (default: 10)')),
                ('is_active', models.BooleanField(default=True)),
                ('invite_code', models.CharField(blank=True, help_text='Unique invite code', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email of invited user', max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('token', models.CharField(help_text='Invitation token', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expiry date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='users.team')),
            ],
            options={
                'db_table': 'team_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('scan_created', 'Scan Created'), ('scan_started', 'Scan Started'), ('scan_completed', 'Scan Completed'), ('scan_failed', 'Scan Failed'), ('scan_cancelled', 'Scan Cancelled'), ('report_downloaded', 'Report Downloaded'), ('dangerous_tool_used', 'Dangerous Tool Used')], max_length=50)),
                ('scan_type', models.CharField(blank=True, choices=[('recon', 'Recon Scan'), ('web', 'Web Scan'), ('api', 'API Scan'), ('vuln', 'Vulnerability Scan'), ('mobile', 'Mobile Scan'), ('custom', 'Custom Scan')], max_length=20)),
                ('target', models.TextField(help_text='Target URL/domain')),
                ('ip_address', models.GenericIPAddressField(help_text='Source IP address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('geo_country', models.CharField(blank=True, help_text='ISO country code', max_length=2)),
                ('geo_city', models.CharField(blank=True, max_length=100)),
                ('geo_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geo_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('vulnerabilities_found', models.IntegerField(default=0)),
                ('severity_critical', models.IntegerField(default=0)),
                ('severity_high', models.IntegerField(default=0)),
                ('severity_medium', models.IntegerField(default=0)),
                ('severity_low', models.IntegerField(default=0)),
                ('used_nuclei', models.BooleanField(default=False)),
                ('used_custom_payloads', models.BooleanField(default=False)),
                ('used_brute_force', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField(blank=True, help_text='Scan duration in seconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deletion_warning_sent', models.BooleanField(default=False, help_text='Warning sent before auto-deletion')),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs_v3', to='scans.scan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scan_audit_logs_v3',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='scan_audit__created_4d1398_idx'), models.Index(fields=['user', '-created_at'], name='scan_audit__user_id_7d3ad7_idx'), models.Index(fields=['ip_address', '-created_at'], name='scan_audit__ip_addr_31ca0b_idx'), models.Index(fields=['action'], name='scan_audit__action_f06300_idx')],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('slack', 'Slack'), ('jira', 'Jira'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('github', 'GitHub'), ('gitlab', 'GitLab'), ('webhook', 'Custom Webhook'), ('email', 'Email Alerts')], max_length=20)),
                ('name', models.CharField(help_text='Integration name/description', max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Integration configuration (API keys, URLs, etc.)')),
                ('events', models.JSONField(default=list, help_text='List of events that trigger this integration')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('total_triggers', models.IntegerField(default=0, help_text='Total times triggered')),
                ('successful_triggers', models.IntegerField(default=0)),
                ('failed_triggers', models.IntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Team integration (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='users.team')),
            ],
            options={
                'db_table': 'integrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'integration_type'], name='integration_user_id_a0bc83_idx'), models.Index(fields=['status'], name='integration_status_7ea6a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('can_create_scans', models.BooleanField(default=True)),
                ('can_view_all_scans', models.BooleanField(default=True)),
                ('can_delete_scans', models.BooleanField(default=False)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
                'ordering': ['-joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
