"""
Background tasks for monitoring scan status and updating database.
"""
import time
import os
import json
import psutil
from pathlib import Path
from datetime import datetime
from threading import Thread
from database import get_db_session
from models import Scan, ScanStatus


def monitor_scan_status(job_id: str, pid: int):
    """
    Background thread to monitor scan process and update database.
    Checks if process is still running and updates status when complete.
    """
    def check_process():
        max_wait = 3600  # Max 1 hour
        start_time = time.time()
        
        while time.time() - start_time < max_wait:
            try:
                proc = psutil.Process(pid)
                if not proc.is_running():
                    # Process finished - update database with final progress
                    with get_db_session() as db:
                        scan = db.query(Scan).filter(Scan.job_id == job_id).first()
                        if scan:  # Remove status check - update regardless of current status
                            # Read final progress from file
                            progress_file = os.path.join("scan_progress", f"{job_id}.json")
                            if os.path.exists(progress_file):
                                try:
                                    with open(progress_file, 'r') as f:
                                        progress_data = json.load(f)
                                    scan.total_urls = progress_data.get("total_urls", 0)
                                    scan.urls_scanned = progress_data.get("urls_scanned", 0)
                                    scan.progress_percentage = 100
                                    scan.vulnerabilities_found = progress_data.get("vulnerabilities_found", 0)
                                except Exception as e:
                                    print(f"Error reading progress file for {job_id}: {e}")
                            
                            # Find existing HTML report generated by main.py OR generate from JSON
                            if not scan.report_path:
                                recon_base = Path("recon_output")
                                base_job_id = job_id[:-1]  # Handle ±1 second timestamp
                                for pattern in [f"{job_id}*", f"{base_job_id}[0-9]*"]:
                                    for scan_dir in recon_base.glob(pattern):
                                        # Look for report.html in scan directory
                                        for report_file in scan_dir.rglob("report.html"):
                                            if report_file.exists():
                                                scan.report_path = str(report_file)
                                                print(f"✓ Found HTML report: {report_file}")
                                                break
                                        
                                        # If no report.html, try to generate from scanner_findings.json
                                        if not scan.report_path:
                                            for findings_file in scan_dir.rglob("*scanner_findings.json"):
                                                if findings_file.exists():
                                                    print(f"📄 Generating HTML report from {findings_file}")
                                                    try:
                                                        from report_generator import generate_html_report
                                                        with open(findings_file, 'r') as f:
                                                            findings_data = json.load(f)
                                                        
                                                        results = findings_data.get("results", findings_data if isinstance(findings_data, list) else [])
                                                        metadata = findings_data.get("metadata", {}) if isinstance(findings_data, dict) else {}
                                                        
                                                        # Generate report in same directory as findings
                                                        report_path = findings_file.parent / "report.html"
                                                        generate_html_report(results, str(report_path), 
                                                                           duration_seconds=metadata.get("duration", 0), 
                                                                           metadata=metadata)
                                                        
                                                        scan.report_path = str(report_path)
                                                        print(f"✓ Generated HTML report: {report_path}")
                                                    except Exception as e:
                                                        print(f"✗ Failed to generate report: {e}")
                                                    break
                                    
                                    if scan.report_path:
                                        break
                            
                            # Mark as completed if not already
                            if scan.status != ScanStatus.COMPLETED:
                                scan.status = ScanStatus.COMPLETED
                                scan.completed_at = datetime.now()
                                print(f"✓ Scan {job_id} marked as completed")
                            
                            db.commit()
                    break
                time.sleep(5)  # Check every 5 seconds
            except psutil.NoSuchProcess:
                # Process already terminated
                with get_db_session() as db:
                    scan = db.query(Scan).filter(Scan.job_id == job_id).first()
                    if scan:  # Remove status check - update regardless of current status
                        # Read final progress from file
                        progress_file = os.path.join("scan_progress", f"{job_id}.json")
                        if os.path.exists(progress_file):
                            try:
                                with open(progress_file, 'r') as f:
                                    progress_data = json.load(f)
                                scan.total_urls = progress_data.get("total_urls", 0)
                                scan.urls_scanned = progress_data.get("urls_scanned", 0)
                                scan.progress_percentage = 100
                                scan.vulnerabilities_found = progress_data.get("vulnerabilities_found", 0)
                            except Exception as e:
                                print(f"Error reading progress file for {job_id}: {e}")
                        
                        # Find existing HTML report generated by main.py OR generate from JSON
                        if not scan.report_path:
                            recon_base = Path("recon_output")
                            base_job_id = job_id[:-1]  # Handle ±1 second timestamp
                            for pattern in [f"{job_id}*", f"{base_job_id}[0-9]*"]:
                                for scan_dir in recon_base.glob(pattern):
                                    # Look for report.html in scan directory
                                    for report_file in scan_dir.rglob("report.html"):
                                        if report_file.exists():
                                            scan.report_path = str(report_file)
                                            print(f"✓ Found HTML report: {report_file}")
                                            break
                                    
                                    # If no report.html, try to generate from scanner_findings.json
                                    if not scan.report_path:
                                        for findings_file in scan_dir.rglob("*scanner_findings.json"):
                                            if findings_file.exists():
                                                print(f"📄 Generating HTML report from {findings_file}")
                                                try:
                                                    from report_generator import generate_html_report
                                                    with open(findings_file, 'r') as f:
                                                        findings_data = json.load(f)
                                                    
                                                    results = findings_data.get("results", findings_data if isinstance(findings_data, list) else [])
                                                    metadata = findings_data.get("metadata", {}) if isinstance(findings_data, dict) else {}
                                                    
                                                    # Generate report in same directory as findings
                                                    report_path = findings_file.parent / "report.html"
                                                    generate_html_report(results, str(report_path), 
                                                                       duration_seconds=metadata.get("duration", 0), 
                                                                       metadata=metadata)
                                                    
                                                    scan.report_path = str(report_path)
                                                    print(f"✓ Generated HTML report: {report_path}")
                                                except Exception as e:
                                                    print(f"✗ Failed to generate report: {e}")
                                                break
                                
                                if scan.report_path:
                                    break
                        
                        # Mark as completed if not already
                        if scan.status != ScanStatus.COMPLETED:
                            scan.status = ScanStatus.COMPLETED
                            scan.completed_at = datetime.now()
                            print(f"✓ Scan {job_id} marked as completed")
                        
                        db.commit()
                break
            except Exception as e:
                print(f"Error monitoring scan {job_id}: {e}")
                time.sleep(10)
    
    thread = Thread(target=check_process, daemon=True)
    thread.start()


def parse_vulnerability_count(report_path: str) -> int:
    """
    Parse HTML report to count vulnerabilities.
    Looks for vulnerability sections in the report.
    """
    try:
        with open(report_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Count different vulnerability markers
        count = 0
        
        # Common patterns in reports
        patterns = [
            '🔴 CRITICAL',
            '🟠 HIGH',
            '🟡 MEDIUM',
            '⚠️ Potential',
            'Vulnerability:',
            'Finding:',
        ]
        
        for pattern in patterns:
            count += content.count(pattern)
        
        return count
    except Exception as e:
        print(f"Error parsing report {report_path}: {e}")
        return 0
