"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-2ooh6&ub7ohd-6j&#+4a#bd3^+h=l^mpenwml=alf0@3vzyo8q'
DEBUG = True
ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'drf_spectacular',
    'channels',
    'corsheaders',
    'users',
    'scans',
    'subscriptions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'bugbounty_arsenal.db',
    }
}

# Cache configuration for rate limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'bugbounty-arsenal-cache',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Enable format suffix patterns (default is True)
    'URL_FORMAT_OVERRIDE': 'format',  # Allow both .json and ?format=json
    # Rate limiting
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',  # General anonymous rate limit
        'user': '1000/hour',  # Authenticated users
        'login': '3/hour',  # Login attempts - 3 tries per hour
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

SPECTACULAR_SETTINGS = {
    'TITLE': 'BugBounty Arsenal API',
    'DESCRIPTION': 'Comprehensive Bug Bounty Security Scanner with automated vulnerability detection',
    'VERSION': '2.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'SWAGGER_UI_FAVICON_HREF': '/static/favicon.ico',
    'REDOC_DIST': 'SIDECAR',
}

_redis_host = os.getenv('REDIS_HOST', 'localhost')
_redis_port = os.getenv('REDIS_PORT', '6379')

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', f'redis://{_redis_host}:{_redis_port}/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', f'redis://{_redis_host}:{_redis_port}/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(os.getenv('REDIS_HOST', 'localhost'), int(os.getenv('REDIS_PORT', _redis_port)))],
        },
    },
}

SCANNER_DETECTOR_MAPPING = {
    'reconnaissance': [
        'subdomain_takeover_detector',
        'dir_listing_detector',
        'security_headers_detector',
        'secret_detector',
        'reflection_detector',
        'cors_detector',
        'graphql_detector',
        'api_security_detector',
    ],
    'web_security': [
        'xss_pattern_detector',
        'sql_pattern_detector',
        'lfi_detector',
        'open_redirect_detector',
        'csrf_detector',
        'header_injection_detector',
        'command_injection_detector',
        'xxe_detector',
        'ssti_detector',
        'prototype_pollution_detector',
        'nosql_injection_detector',
        'cache_poisoning_detector',
        'idor_detector',
        'auth_bypass_detector',
        'fuzz_detector',
        'file_upload_detector',
    ],
    'api_security': [
        'api_security_detector',
        'graphql_detector',
        'graphql_injection_detector',
        'jwt_detector',
        'jwt_vulnerability_scanner',
        'oauth_detector',
        'cors_detector',
        'rate_limit_bypass_detector',
        'idor_detector',
        'nosql_injection_detector',
    ],
    'mobile': [
        'api_security_detector',
        'jwt_detector',
        'oauth_detector',
        'secret_detector',
        'idor_detector',
        'rate_limit_bypass_detector',
    ],
    'comprehensive': [
        'subdomain_takeover_detector',
        'dir_listing_detector',
        'security_headers_detector',
        'secret_detector',
        'reflection_detector',
        'cors_detector',
        'graphql_detector',
        'api_security_detector',
        'xss_pattern_detector',
        'sql_pattern_detector',
        'lfi_detector',
        'open_redirect_detector',
        'csrf_detector',
        'header_injection_detector',
        'command_injection_detector',
        'xxe_detector',
        'ssti_detector',
        'prototype_pollution_detector',
        'nosql_injection_detector',
        'cache_poisoning_detector',
        'idor_detector',
        'auth_bypass_detector',
        'fuzz_detector',
        'file_upload_detector',
        'ssrf_detector',
        'advanced_ssrf_detector',
        'ssrf_oob_detector',
        'jwt_detector',
        'jwt_vulnerability_scanner',
        'oauth_detector',
        'race_condition_detector',
        'graphql_injection_detector',
        'brute_force_detector',
        'rate_limit_bypass_detector',
        'injector',
        'cve_database_detector',
    ],
}

# Note: mobile placeholders removed to avoid missing modules

# ===========================
# STRIPE PAYMENT SETTINGS
# ===========================
STRIPE_SECRET_KEY = 'sk_test_51Sk1ua9851nFpwhtUsZP8XfQxdKL6SxTnADMeBT8xjr6NFzxnvYcyZXDiMnsHdF7mGm6ZxMLc4Re9DvBsCA5n7bM00Jk0H2GCA'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51Sk1ua9851nFpwhtxsuyQjH4hqHFMbyRLj3973UQsBVpz9ycU1HhawLZ2WN02gRS7idLcEkcRizMYEyzmJUhyqKs00IXwAixSA'
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_...')  # Add webhook secret

# Frontend URL for redirects
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')

# ===========================
# TWILIO SMS VERIFICATION
# ===========================
# Cost: ~$0.01 per SMS
# Development mode: Set TWILIO_ENABLED=False to use console/email fallback
TWILIO_ENABLED = os.getenv('TWILIO_ENABLED', 'False') == 'True'
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER', '')  # E.g., +15551234567

# ===========================
# OPENCORPORATES API
# ===========================
# Free tier: 500 requests/month
# Paid tier: $99/month for 10,000 requests
# Used for company verification (Enterprise plan only)
OPENCORPORATES_API_KEY = os.getenv('OPENCORPORATES_API_KEY', '')
OPENCORPORATES_ENABLED = bool(OPENCORPORATES_API_KEY)
