# Generated by Django 6.0 on 2025-12-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20251204_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['order', 'price']},
        ),
        migrations.AddField(
            model_name='plan',
            name='allowed_scan_types',
            field=models.JSONField(default=list, help_text='Allowed scan types: web, api, mobile, etc.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='concurrent_scans',
            field=models.IntegerField(default=1, help_text='Number of concurrent scans allowed'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, help_text='Plan description for landing page'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Show "Most Popular" badge'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_detectors',
            field=models.IntegerField(default=15, help_text='Maximum detectors available (-1 = all)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_urls_per_scan',
            field=models.IntegerField(default=10, help_text='Maximum URLs per scan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order on pricing page'),
        ),
        migrations.AddField(
            model_name='plan',
            name='retention_days',
            field=models.IntegerField(default=7, help_text='How many days to keep scan results'),
        ),
        migrations.AddField(
            model_name='plan',
            name='scans_per_day',
            field=models.IntegerField(default=3, help_text='Daily scan limit (-1 = unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='scans_per_month',
            field=models.IntegerField(default=100, help_text='Monthly scan limit (-1 = unlimited)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage_limit_mb',
            field=models.IntegerField(default=100, help_text='Storage limit in MB for scan results'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.JSONField(default=list, help_text='List of feature names for display'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='limits',
            field=models.JSONField(default=dict, help_text='Legacy limits field (deprecated)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly price in USD', max_digits=10),
        ),
    ]
