# Generated by Django 6.0 on 2025-12-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='allowed_scan_types',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='limits',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_detectors',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_urls_per_scan',
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_dangerous_tools',
            field=models.BooleanField(default=False, help_text='Allow Nuclei, custom payloads (Enterprise only)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_integrations',
            field=models.BooleanField(default=False, help_text='Enable third-party integrations (Pro & Enterprise)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='allow_teams',
            field=models.BooleanField(default=False, help_text='Enable team features (Pro & Enterprise)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_integrations',
            field=models.IntegerField(default=0, help_text='Maximum active integrations'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_team_members',
            field=models.IntegerField(default=0, help_text='Maximum team members (0 = no teams)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_monthly_reset',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='scans_used_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='scans_per_month',
            field=models.IntegerField(default=10, help_text='Monthly scan limit (-1 = unlimited)'),
        ),
    ]
