# Generated by Django 6.0 on 2025-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async execution', max_length=100, null=True),
        ),
    ]
