# Generated by Django 6.0 on 2025-12-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_scan_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='current_step',
            field=models.CharField(blank=True, help_text='Current scan step/phase', max_length=200),
        ),
        migrations.AddField(
            model_name='scan',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this scan result will be auto-deleted', null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='progress',
            field=models.IntegerField(default=0, help_text='Scan progress percentage (0-100)'),
        ),
        migrations.AddField(
            model_name='scan',
            name='raw_results',
            field=models.JSONField(blank=True, default=dict, help_text='Full scan results data'),
        ),
        migrations.AddField(
            model_name='scan',
            name='report_size_bytes',
            field=models.BigIntegerField(default=0, help_text='Total size of all report files in bytes'),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Vulnerability type/title', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='low', max_length=20)),
                ('detector', models.CharField(blank=True, help_text='Which detector found this', max_length=100)),
                ('url', models.TextField(blank=True, help_text='Vulnerable URL')),
                ('payload', models.TextField(blank=True, help_text='Payload used for exploitation')),
                ('evidence', models.TextField(blank=True, help_text='Evidence of the vulnerability')),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full raw finding data')),
                ('is_verified', models.BooleanField(default=False, help_text='User verified this finding')),
                ('notes', models.TextField(blank=True, help_text='User notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='scans.scan')),
            ],
            options={
                'db_table': 'vulnerabilities',
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['scan', 'severity'], name='vulnerabili_scan_id_d13ec1_idx'), models.Index(fields=['detector'], name='vulnerabili_detecto_7880a3_idx')],
            },
        ),
    ]
