# Generated by Django 6.0 on 2025-12-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0005_alter_vulnerability_payload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('recon', 'Reconnaissance Scan'), ('web', 'Web Application Scan'), ('api', 'API Security Scan'), ('vuln', 'Vulnerability Scan'), ('mobile', 'Mobile Security Scan'), ('custom', 'Custom Scan (All Tools)')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_plan', models.CharField(choices=[('free', 'Free Plan'), ('pro', 'Pro Plan'), ('enterprise', 'Enterprise Plan')], default='free', help_text='Minimum plan required to use this category', max_length=20)),
                ('icon', models.CharField(default='🔍', help_text='Emoji icon for UI display', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('detector_count', models.IntegerField(default=0, help_text='Number of detectors in this category (auto-calculated)')),
                ('order', models.IntegerField(default=0, help_text='Display order in UI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scan Category',
                'verbose_name_plural': 'Scan Categories',
                'db_table': 'scan_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='selected_detectors',
            field=models.JSONField(blank=True, default=list, help_text='List of detector names to run (empty = all for category)'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(blank=True, choices=[('reconnaissance', 'Reconnaissance'), ('web_security', 'Web Security'), ('vulnerability', 'Vulnerability Scan'), ('api_security', 'API Security'), ('mobile', 'Mobile Security')], default='web_security', help_text='DEPRECATED: Use scan_category instead', max_length=50),
        ),
        migrations.CreateModel(
            name='DetectorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Python module name (e.g., xss_pattern_detector)', max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], default='medium', help_text='Maximum severity of vulnerabilities this detector can find', max_length=20)),
                ('tags', models.JSONField(default=list, help_text='Tags for filtering (e.g., ["injection", "owasp-top10"])')),
                ('is_dangerous', models.BooleanField(default=False, help_text='Requires Enterprise plan (nuclei, brute force, custom payloads)')),
                ('requires_oob', models.BooleanField(default=False, help_text='Requires out-of-band interaction (Interactsh, Burp Collaborator)')),
                ('execution_order', models.IntegerField(default=100, help_text='Order of execution (lower runs first)')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Maximum execution time per target')),
                ('max_concurrency', models.IntegerField(default=10, help_text='Maximum concurrent requests')),
                ('is_active', models.BooleanField(default=True)),
                ('is_beta', models.BooleanField(default=False, help_text='Beta features may have bugs or incomplete functionality')),
                ('total_executions', models.IntegerField(default=0)),
                ('total_findings', models.IntegerField(default=0)),
                ('average_execution_time', models.FloatField(default=0.0, help_text='In seconds')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(help_text='Categories this detector belongs to', related_name='detectors', to='scans.scancategory')),
            ],
            options={
                'verbose_name': 'Detector Configuration',
                'verbose_name_plural': 'Detector Configurations',
                'db_table': 'detector_configs',
                'ordering': ['execution_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='scan',
            name='scan_category',
            field=models.ForeignKey(blank=True, help_text='V3.0 scan category (replaces scan_type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_scans', to='scans.scancategory'),
        ),
        migrations.CreateModel(
            name='CategoryDetectorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('is_enabled', models.BooleanField(default=True, help_text='Can be disabled per category without removing from category')),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.detectorconfig')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scans.scancategory')),
            ],
            options={
                'db_table': 'category_detector_orders',
                'ordering': ['order'],
                'unique_together': {('category', 'detector')},
            },
        ),
    ]
