# Generated by Django 6.0 on 2026-01-03 17:05

from django.db import migrations
from django.conf import settings


def populate_data(apps, schema_editor):
    """Populate initial Plans and ScanCategories"""
    Plan = apps.get_model('subscriptions', 'Plan')
    ScanCategory = apps.get_model('scans', 'ScanCategory')
    
    # Create Plans (only if they don't exist)
    if not Plan.objects.exists():
        Plan.objects.create(
            name='free',
            display_name='Free',
            price=0,
            stripe_price_id=getattr(settings, 'STRIPE_PRICE_FREE', ''),
            daily_scan_limit=5,
            monthly_scan_limit=50,
            concurrent_scans=1,
            storage_limit_mb=100,
            retention_days=7,
            features=['Basic vulnerability scanning', 'Community support', 'Limited detectors'],
            allow_teams=False,
            max_team_members=1,
            allow_integrations=False,
            max_integrations=0,
            allow_dangerous_tools=False
        )
        
        Plan.objects.create(
            name='pro',
            display_name='Pro',
            price=19,
            stripe_price_id=getattr(settings, 'STRIPE_PRICE_PRO', ''),
            daily_scan_limit=50,
            monthly_scan_limit=1000,
            concurrent_scans=5,
            storage_limit_mb=1000,
            retention_days=30,
            features=['Advanced scanning', 'Priority support', 'All detectors', 'API access'],
            allow_teams=True,
            max_team_members=5,
            allow_integrations=True,
            max_integrations=5,
            allow_dangerous_tools=False
        )
        
        Plan.objects.create(
            name='enterprise',
            display_name='Enterprise',
            price=99,
            stripe_price_id=getattr(settings, 'STRIPE_PRICE_ENTERPRISE', ''),
            daily_scan_limit=999999,
            monthly_scan_limit=999999,
            concurrent_scans=20,
            storage_limit_mb=10000,
            retention_days=365,
            features=['Unlimited scanning', '24/7 support', 'All features', 'Custom integrations', 'Dangerous tools'],
            allow_teams=True,
            max_team_members=50,
            allow_integrations=True,
            max_integrations=999,
            allow_dangerous_tools=True,
            is_enterprise_only=True
        )
    
    # Create ScanCategories (only if they don't exist)
    if not ScanCategory.objects.exists():
        ScanCategory.objects.create(
            name='0-Day Hunting',
            slug='zero_day',
            description='Advanced techniques for discovering zero-day vulnerabilities',
            icon_emoji='🎯',
            required_plan='pro',
            detector_count=15,
            dangerous_detector_count=5,
            is_enterprise_only=False
        )
        
        ScanCategory.objects.create(
            name='Web Application Security',
            slug='web_app',
            description='Comprehensive web application security testing',
            icon_emoji='🌐',
            required_plan='free',
            detector_count=25,
            dangerous_detector_count=0,
            is_enterprise_only=False
        )
        
        ScanCategory.objects.create(
            name='API Security',
            slug='api',
            description='REST, GraphQL, and API endpoint security',
            icon_emoji='🔌',
            required_plan='free',
            detector_count=12,
            dangerous_detector_count=0,
            is_enterprise_only=False
        )
        
        ScanCategory.objects.create(
            name='Authentication & Session',
            slug='auth',
            description='Authentication bypass and session management flaws',
            icon_emoji='🔐',
            required_plan='free',
            detector_count=10,
            dangerous_detector_count=0,
            is_enterprise_only=False
        )
        
        ScanCategory.objects.create(
            name='Injection Attacks',
            slug='injection',
            description='SQL, NoSQL, Command, and other injection vulnerabilities',
            icon_emoji='💉',
            required_plan='free',
            detector_count=18,
            dangerous_detector_count=3,
            is_enterprise_only=False
        )


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0006_scancategory_scan_selected_detectors_and_more'),
        ('subscriptions', '0001_initial'),  # Make sure subscriptions app is migrated first
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=migrations.RunPython.noop),
    ]
